'use client';
import {useState} from 'react';
import {Well,distance} from '@/lib/data';
export default function WellMap({active,nearby,radius,selected,onSelect}:{active:Well;nearby:Well[];radius:number;selected:string;onSelect:(s:string)=>void}){
 const [zoom,setZoom]=useState(0),[offline,setOffline]=useState(false);
 const z=Math.max(8,Math.min(15,(radius<=5?12:radius<=10?11:10)+zoom)),n=2**z;
 const point=(lat:number,lon:number)=>[(lon+180)/360*n*256,(1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*n*256];
 const center=point(active.lat,active.lon),left=center[0]-380,top=center[1]-200;
 const px=(w:Well)=>{const p=point(w.lat,w.lon);return[p[0]-left,p[1]-top]};
 const tiles=[];for(let x=Math.floor(left/256);x<=Math.floor((left+760)/256);x++)for(let y=Math.floor(top/256);y<=Math.floor((top+400)/256);y++)tiles.push({x,y});
 const rad=radius*1000/(156543.03392*Math.cos(active.lat*Math.PI/180)/2**z),w=nearby.find(w=>w.id===selected);
 return <div className="map-wrap"><svg className="geographic-map" viewBox="0 0 760 400" role="img" aria-label={`Geospatial map of ${nearby.length} offset wells within ${radius} kilometres`}><rect width="760" height="400" fill="#e9efef"/>{tiles.map(t=><image className="map-tile" key={`${z}-${t.x}-${t.y}`} href={`https://tile.openstreetmap.org/${z}/${t.x}/${t.y}.png`} x={t.x*256-left} y={t.y*256-top} width="256" height="256" onError={()=>setOffline(true)}/>)}<circle cx="380" cy="200" r={rad} fill="#38b2a0" fillOpacity=".06" stroke="#419a93" strokeDasharray="5 7" strokeWidth="1.4"/>{w&&<line x1="380" y1="200" x2={px(w)[0]} y2={px(w)[1]} stroke="#738b9b" strokeDasharray="4 6"/>}{[active,...nearby].map(w=>{const [x,y]=px(w),isActive=w.id===active.id;return <g key={w.id} transform={`translate(${x},${y})`} role="button" tabIndex={0} aria-label={`Select ${w.id}`} onClick={()=>onSelect(w.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(w.id)}}} style={{cursor:'pointer'}}><circle r={isActive?11:8} fill={isActive?'#169d89':w.id===selected?'#d69d44':'#365c80'} stroke="white" strokeWidth="3"/><rect x={isActive?-53:-27} y="-35" width={isActive?106:54} height="21" fill="white" stroke="#dce4e7" rx="4"/><text textAnchor="middle" y="-21" fill="#345269" fontSize="10" fontWeight="700">{w.id}{isActive?' · ACTIVE':''}</text></g>})}<text x="20" y="28" fontSize="12" fill="#486a7f">N ↑</text></svg><div className="map-zoom"><button aria-label="Zoom in" disabled={z>=15} onClick={()=>setZoom(zoom+1)}>+</button><button aria-label="Zoom out" disabled={z<=8} onClick={()=>setZoom(zoom-1)}>−</button></div><a className="map-attribution" href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a>{w&&<div className="map-selection"><span className="badge teal">SELECTED OFFSET</span><b>{w.id} <small>{distance(active,w).toFixed(1)} km away</small></b><span>{w.name}</span></div>}{offline&&<div className="map-warning">Basemap unavailable. Coordinate markers remain active; use the inventory below.</div>}</div>
}
