export type Well={id:string;name:string;lat:number;lon:number;td:number;formation:string;top:number;mud:number;porosity:number;casing:string;cement:string};
export type Event={id:string;well:string;type:string;formation:string;from:number;to:number;basis:string;severity:string;action:string;outcome:string;source:string;page:number;excerpt:string;reportId?:string;reviewed?:boolean;sourceUrl?:string};
export const wells:Well[]=[
{id:'NW-01',name:'Duliajan exploration',lat:27.35,lon:95.32,td:2850,formation:'Barail sandstone',top:2100,mud:1.18,porosity:18,casing:'9⅝ in @ 1,850 m',cement:'Two-stage • evaluated'},
{id:'OW-02',name:'Duliajan east',lat:27.374,lon:95.346,td:2920,formation:'Barail sandstone',top:2120,mud:1.2,porosity:21,casing:'9⅝ in @ 1,900 m',cement:'Two-stage • good bond'},
{id:'OW-03',name:'Duliajan south',lat:27.316,lon:95.305,td:2810,formation:'Barail sandstone',top:2090,mud:1.16,porosity:19,casing:'9⅝ in @ 1,820 m',cement:'Single-stage • channeling'},
{id:'OW-04',name:'Naharkatiya north',lat:27.399,lon:95.279,td:3200,formation:'Barail sandstone',top:2140,mud:1.23,porosity:16,casing:'9⅝ in @ 1,960 m',cement:'Two-stage • good bond'},
{id:'OW-05',name:'Tengakhat west',lat:27.34,lon:95.235,td:2760,formation:'Barail sandstone',top:2070,mud:1.19,porosity:17,casing:'9⅝ in @ 1,800 m',cement:'Two-stage • evaluated'},
{id:'OW-06',name:'Eastern appraisal',lat:27.432,lon:95.412,td:3100,formation:'Barail sandstone',top:2170,mud:1.25,porosity:14,casing:'9⅝ in @ 2,010 m',cement:'Single-stage • evaluated'},
{id:'OW-07',name:'Southern appraisal',lat:27.21,lon:95.37,td:2990,formation:'Barail sandstone',top:2150,mud:1.22,porosity:15,casing:'9⅝ in @ 1,940 m',cement:'Two-stage • good bond'}];
const raw=[['OW-02','Mud loss',2160,2185,'High','Reviewed loss-control plan and adjusted fluid program','Circulation restored; 4 h NPT'],['OW-03','Mud loss',2135,2155,'High','Reviewed loss trend and applied approved treatment','Losses stabilized; 3 h NPT'],['OW-04','Stuck pipe',2260,2280,'High','Reviewed differential pressure and followed freeing procedure','Pipe freed; 9 h NPT'],['OW-05','Torque spike',2195,2210,'Medium','Reviewed hole cleaning and drilling parameters','Torque returned to baseline; 2 h NPT'],['OW-06','Overpressure',2320,2340,'High','Reviewed pressure indicators with well-control team','Well stabilized; 6 h NPT'],['OW-03','Cementing issue',2095,2110,'Medium','Evaluated cement bond log and planned remediation','Remedial cement job completed'],['OW-04','Kick',2350,2365,'High','Activated approved well-control procedure','Well secured; 8 h NPT'],['OW-07','Mud loss',2185,2210,'High','Reviewed loss-control readiness and fluid properties','Partial returns recovered; 5 h NPT'],['OW-02','Torque spike',2275,2290,'Medium','Reviewed cuttings loading and hole condition','Stable drilling resumed'],['OW-05','Stuck pipe',2245,2260,'High','Followed approved stuck-pipe contingency','Recovered assembly; 7 h NPT']];
export const seedEvents:Event[]=raw.map((r,i)=>({id:`seed-${i}`,well:String(r[0]),type:String(r[1]),formation:'Barail sandstone',from:Number(r[2]),to:Number(r[3]),basis:'TVD',severity:String(r[4]),action:String(r[5]),outcome:String(r[6]),source:`${r[0]} · synthetic DDR`,page:1,sourceUrl:`/reports/incident-${i+1}.pdf`,excerpt:`SYNTHETIC DEMONSTRATION REPORT\nWell: ${r[0]}\nFormation: Barail sandstone\nDepth: ${r[2]}–${r[3]} m TVD\nEvent: ${r[1]}\nSeverity: ${r[4]}\nAction: ${r[5]}\nOutcome: ${r[6]}`,reviewed:true}));
export const types=['Mud loss','Stuck pipe','Overpressure','Torque spike','Cementing issue','Kick'];
export function distance(a:Well,b:Well){const rad=Math.PI/180,dlat=(a.lat-b.lat)*rad,dlon=(a.lon-b.lon)*rad;return 6371*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlon/2)**2));}
export function risks(events:Event[],active:Well,depth:number,radius:number){return events.filter(e=>{const w=wells.find(w=>w.id===e.well);if(!w||w.id===active.id||distance(active,w)>radius||e.formation.trim().toLowerCase()!==active.formation.trim().toLowerCase()||e.basis!=='TVD')return false;const start=active.top+(e.from-w.top),end=active.top+(e.to-w.top);return depth>=start-100&&depth<=end;}).map(e=>{const w=wells.find(w=>w.id===e.well)!;const start=active.top+e.from-w.top;return {...e,projected:start,ahead:start-depth,level:depth>=start-40?'High':'Watch'};});}

export const demoScenarios=[
 {id:'mud-loss',title:'Mud loss',depth:2120,radius:10,eventId:'seed-0',description:'Two offset wells support an approaching mud-loss warning.'},
 {id:'stuck-pipe',title:'Stuck pipe',depth:2200,radius:10,eventId:'seed-2',description:'Inspect an incident 20 m ahead in the projected formation interval.'},
 {id:'kick',title:'Kick',depth:2290,radius:10,eventId:'seed-6',description:'Review historical kick evidence before the projected interval.'}
];
export function explainMatch(e:Event,active:Well,depth:number,radius:number){const w=wells.find(w=>w.id===e.well);if(!w)return {included:false,distance:NaN,projected:null,end:null,gap:null,checks:[{label:'Known offset well',pass:false,detail:'Well is not in the inventory.'}]};const km=distance(active,w),projected=active.top+e.from-w.top,end=active.top+e.to-w.top,gap=projected-depth;const checks=[
 {label:'Offset well',pass:w.id!==active.id,detail:w.id===active.id?'Same as the active well.':`${w.id} compared with ${active.id}`},
 {label:'Distance',pass:km<=radius,detail:`${km.toFixed(1)} km away / ${radius} km radius`},
 {label:'Formation',pass:e.formation.trim().toLowerCase()===active.formation.trim().toLowerCase(),detail:e.formation},
 {label:'Depth basis',pass:e.basis==='TVD',detail:e.basis==='TVD'?'TVD available; formation-top alignment applied.':'MD only; verified TVD conversion required.'},
 {label:'Alert window',pass:e.basis==='TVD'&&depth>=projected-100&&depth<=end,detail:e.basis!=='TVD'?'Not evaluated without TVD.':depth>end?'Projected interval already passed.':gap>100?`${gap} m ahead; outside the 100 m look-ahead.`:gap>0?`${gap} m before projected interval.`:'Current depth is inside the projected interval.'}
 ];return {included:checks.every(c=>c.pass),distance:km,projected:e.basis==='TVD'?projected:null,end:e.basis==='TVD'?end:null,gap:e.basis==='TVD'?gap:null,checks};}
